# Generated by Django 5.0.6 on 2024-07-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0002_alter_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.CharField(max_length=5),
        ),
    ]
